# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

#External API keys
external_api_keys: &external_api_keys
  google_analytics_code:
  google_maps_api_key:
  recaptcha:
    sitekey:
    secret:
  elixir_aai: # LS-Login authentication config
    client_id: # client id
    secret: # secret
  oidc: # OpenID Connect authentication config
    label:             # name of auth provider to display to users e.g. AAF (Australia)
    logo:              # optional path to logo to display to users under app/assets/images e.g. dresa/aaf_service_223x54.png
    client_id:         # client id
    secret:            # secret
    issuer:            # issuer uri e.g. https://central.test.aaf.edu.au
  oidc2: # Secondary OpenID Connect authentication config
    label:             # name of auth provider to display to users e.g. Tuakiri (NZ)
    logo:              # optional path to logo to display to users under app/assets/images
    client_id:         # client id
    secret:            # secret
    issuer:            # issuer uri e.g. https://openidconnect.test.tuakiri.ac.nz
  bioportal_api_key:
  fairsharing:
    username:
    password:
  gpt_api_key:
  willma_api_key:
  indico_api_token:   # begins by 'indp_', cf. https://docs.getindico.io/en/stable/http-api/access/#api-token-authentication
  orcid:
    client_id:
    secret:
    host:

#Internal config
development:
  <<: *external_api_keys
  secret_key_base: a_really_long_string_here
  database:
    :host: localhost
    :name: tess_development
    :username: tess_user
    :password: awesome_secure_password

test:
  <<: *external_api_keys
  secret_key_base: another_really_long_string
  database:
    :host: localhost
    :name: tess_test
    :username: tess_user
    :password: awesome_secure_password

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *external_api_keys
  secret_key_base: # ! Set production secret here
  smtp:
    :address:              smtp.gmail.com
    :user_name:            <%= ENV["PRODUCTION_GMAIL_USERNAME"] %>
    :password:             <%= ENV["PRODUCTION_GMAIL_PASSWORD"] %>
    :port:                 587
    :domain:               gmail.com
    :authentication:       plain
    :enable_starttls_auto: true
  google_analytics_code: <%= ENV["PRODUCTION_GANAL_CODE"] %>
  google_maps_api_key:   <%= ENV["PRODUCTION_GMAPS_KEY"] %>
  database:
    :host: localhost
    :name: tess_production
    :username: tess_user
    :password: awesome_secure_password