# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

#External API keys
external_api_keys: &external_api_keys
  google_maps_api_key:
  recaptcha:
    sitekey:
    secret:
  elixir_aai:
    client_id: #client
    secret: #secret
    redirect_uri: #redirect_uri e.g. https://<host address>/users/auth/elixir_aai/callback
  bioportal_api_key:

#Internal config
development:
  <<: *external_api_keys
  secret_key_base: a_really_long_string_here
  database:
    :name: tess_development
    :username: tess_user
    :password: awesome_secure_password
  smtp:
    :address: smtp.yourprovider.com
    :username: your_username
    :password: another_awesome_secure_password

test:
  <<: *external_api_keys
  secret_key_base: another_really_long_string
  database:
    :name: tess_test
    :username: tess_user
    :password: awesome_secure_password
  solr:
    :username: solr_server_username
    :password: solr_server_password

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *external_api_keys
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  database:
    :name: tess_production
    :username: <%= ENV["PRODUCTION_DB_USER"] %>
    :password: <%= ENV["PRODUCTION_DB_PASSWORD"] %>
  smtp:
    :address: localhost
    :user_name:
    :password:
    :port: 25
    :domain: localhost.localdomain
    :authentication:
    :enable_starttls_auto: true
  google_analytics_code:
