notspecified:
  title: Not specified
  description: Difficulty level not specified
beginner:
  title: Beginner
  description: The owest level of difficulty; this content is suitable for beginners on the topic.
intermediate:
  title: Intermediate
  description: Intermediate level of difficulty; suitable for people who already have some knowledge of the topic.
advanced:
  title: Advanced
  description: The highest level of difficulty; this content is suitable for people who have a substantial knowledge of the topic.
